rm(list=ls(all=TRUE))
getwd()
setwd("C:\\Users\\sai\\test\\ProgrammingAssignment2")
source("C:\\Users\\sai\\test\\ProgrammingAssignment2\\cachematrix.R")
matrix <- makeCacheMatrix(matrix(1:4,2,2))
matrix$get()
matrix$getinverse()
cacheSolve(matrix)
cacheSolve(matrix)
matrix$getinverse()
matrix$set(matrix(c(2,2,1,4),2,2))
matrix$get()
matrix$getinverse()
cacheSolve(matrix)
cacheSolve(matrix)
matrix$getinverse()
